name: 1.0$(Rev:.r)

# simplified trigger (implied branch)
trigger:
    branches:
      include:
      - main 

# equivalents trigger
# trigger:
#  branches:
#    include:
#    - main

variables:
  name: martin

pool:
  vmImage: ubuntu-latest

jobs:

- job: job-1
  dependsOn: none
  steps:

    - script: echo "Runs task, $(name)"
- job: Linux
- template: variables/variables.yml
  pool:
    vmImage: variables.vmImage
  steps:
  - template: steps/build.yml
  - script: sign
